version: 0.0
os: linux
files:
  - source: /build_artifacts/*.jar
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
